### ISSUE TITLE
GeoIP still broken after the fix

### ISSUE THREAD

**Issue by EagL3-GIT** [4drian3d/EpicGuard#120]
[18:06:53 INFO]: [EpicGuard] Enabling EpicGuard v7.5.1
[18:06:53 INFO]: [EpicGuard] Running on: git-Paper-291 (MC: 1.20.2)
[18:06:53 INFO]: [EpicGuard] Loading configuration...
[18:06:54 INFO]: [EpicGuard] Initializing managers...
[18:06:54 INFO]: [EpicGuard] This product includes GeoLite2 data created by MaxMind, available from https://www.maxmind.com
[18:06:54 INFO]: [EpicGuard] Downloading the GeoIP database file: GeoLite2-Country.mmdb
[18:06:54 INFO]: [EpicGuard] Downloading file from https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country&license_key=&suffix=tar.gz to /hlserver/27082/plugins/EpicGuard/data/GeoLite2-Country.tar.gz
[18:06:54 ERROR]: [EpicGuard] An error occurred in EpicGuard v7.5.1
[18:06:54 ERROR]: [EpicGuard] > Details: Error while getting the GeoIP databases, please check your internet connection.
[18:06:54 ERROR]: [EpicGuard] > Platform: git-Paper-291 (MC: 1.20.2)
[18:06:54 ERROR]: [EpicGuard] > Stacktrace:
[18:06:54 ERROR]: [EpicGuard]
java.io.IOException: Server returned HTTP response code: 401 for URL: https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country&license_key=&suffix=tar.gz
at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1997) ~[?:?]
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589) ~[?:?]
at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224) ~[?:?]
at me.xneox.epicguard.core.util.FileUtils.downloadFile(FileUtils.java:43) ~[EpicGuardPaper-7.5.1.jar:?]
at me.xneox.epicguard.core.manager.GeoManager.downloadDatabase(GeoManager.java:91) ~[EpicGuardPaper-7.5.1.jar:?]
at me.xneox.epicguard.core.manager.GeoManager.<init>(GeoManager.java:67) ~[EpicGuardPaper-7.5.1.jar:?]
at me.xneox.epicguard.core.EpicGuard.startup(EpicGuard.java:75) ~[EpicGuardPaper-7.5.1.jar:?]
at me.xneox.epicguard.core.EpicGuard.<init>(EpicGuard.java:64) ~[EpicGuardPaper-7.5.1.jar:?]
at me.xneox.epicguard.paper.EpicGuardPaper.onEnable(EpicGuardPaper.java:45) ~[EpicGuardPaper-7.5.1.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.2.jar:git-Paper-291]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.2.jar:git-Paper-291]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:646) ~[paper-1.20.2.jar:git-Paper-291]
at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:557) ~[paper-1.20.2.jar:git-Paper-291]
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:627) ~[paper-1.20.2.jar:git-Paper-291]
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[paper-1.20.2.jar:git-Paper-291]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.2.jar:git-Paper-291]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-291]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-291]
at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by 4drian3d** [comment]
As indicated in the commit and the new configuration option, a personal key is now required to access the Max Mind GeoIP service. So far we have been using one here that comes from the beginning of the plugin, contrary to other plugins with similar functions that require to specify a personal key to avoid this kind of cases

**Comment by EagL3-GIT** [comment]
Oh okay, so like where do I get that personal key?

**Comment by ilgrandeanonimo** [comment]
https://www.maxmind.com/en/geolite2/signup?utm_source=kb&utm_medium=kb-link&utm_campaign=kb-create-account
