### ISSUE TITLE
Couldn't pass ProxyInitializeEvent to epicguard

### ISSUE THREAD

**Issue by fadfhkdfga** [4drian3d/EpicGuard#146]
Couldn't pass ProxyInitializeEvent to epicguard
java.lang.NoClassDefFoundError: me/xneox/epicguard/libs/io/leangen/geantyref/TypeToken
        at me.xneox.epicguard.velocity.EpicGuardVelocity$CommandRegister.register(EpicGuardVelocity.java:133) ~[?:?]
        at me.xneox.epicguard.velocity.EpicGuardVelocity.onEnable(EpicGuardVelocity.java:77) ~[?:?]
        at me.xneox.epicguard.velocity.Lmbda$15.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.3.0-SNAPSHOT-345.jar:3.3.0-SNAPSHOT (git-38558783-b345)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[velocity-3.3.0-SNAPSHOT-345.jar:3.3.0-SNAPSHOT (git-38558783-b345)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[velocity-3.3.0-SNAPSHOT-345.jar:3.3.0-SNAPSHOT (git-38558783-b345)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:842) [?:?]
Caused by: java.lang.ClassNotFoundException: me.xneox.epicguard.libs.io.leangen.geantyref.TypeToken
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:87) ~[velocity-3.3.0-SNAPSHOT-345.jar:3.3.0-SNAPSHOT (git-38558783-b345)]

**Comment by 4drian3d** [comment]
Are you sure you are using the latest version of EpicGuard? We no longer use the relocated version of geantyref, but the version included in Velocity
